## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.100.99.127:3306/lot_share?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: luojs  # 替 换真实用户名
    password: 123456 # 届时替换真实密码
    driver-class-name: com.mysql.jdbc.Driver

## Mybatis 配置
mybatis:
  typeAliasesPackage: space.qmen.lot.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射

favorites:
  file:
    save:
      path: static/file/logo/
    access:
      url: http://47.100.99.127:8888/file/logo/
  base:
    path: http://47.100.99.127:8888/